/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package edu.jdc.formularuios;

import edu.jdc.clases.Bodega;
import edu.jdc.clases.Ventas;
import edu.jdc.daos.DaoVentas;
import static java.lang.Integer.parseInt;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class FrmAdministarVentas extends javax.swing.JInternalFrame {

    private String[] textoColumnas = {"Codigo Venta", "Codigo Bodega", "Cantidad Venta", "Fecha Venta", "Actualizar", "Borrar"};
    private DaoVentas objMiDao;
    private List<Ventas> arregloVentas;
    private Ventas objVentas;
    
    private DefaultTableModel miModelito = new DefaultTableModel(textoColumnas, 0){
        @Override

        public boolean isCellEditable(int row, int column) {
            return false;
        }

        @Override
        public Class<?> getColumnClass(int columIndex) {

            if (columIndex == 4) {
                return ImageIcon.class;
            }

            if (columIndex == 5) {
                return ImageIcon.class;
            }
            return Object.class;
        }
        
    };
    
    
    public FrmAdministarVentas() {
        initComponents();
        
        objMiDao = new DaoVentas();
        arregloVentas = new ArrayList<>();
        tablaSalida.setModel(miModelito);
        llenarTabla();
    }
    
    private void llenarTabla() {
        miModelito.setRowCount(0);
        arregloVentas = objMiDao.consultar("");

        String nombreActualizar = "/edu/jdc/imagenes/editar.png";
        String nombreBorrar = "/edu/jdc/imagenes/borrar.png";

        String rutaOmagenActu = this.getClass().getResource(nombreActualizar).getPath();
        String rutaOmagenBorr = this.getClass().getResource(nombreBorrar).getPath();

        ImageIcon iconActualizar = new ImageIcon(rutaOmagenActu);
        ImageIcon iconBorrar = new ImageIcon(rutaOmagenBorr);

        for (Ventas objMiVenta : arregloVentas) {
            Object[] miFila = new Object[6];

            miFila[0] = objMiVenta.getCodVenta();
            miFila[1] = objMiVenta.getCodBodega();
            miFila[2] = objMiVenta.getCantidadVenta();
            miFila[3] = objMiVenta.getFechaVenta();
            miFila[4] = iconActualizar;
            miFila[5] = iconBorrar;

            miModelito.addRow(miFila);

        }

    }
    private void cerrarVentana(){
        int opcion = 0;
        String[] textoBotones={"Aceptar", "Cancelar"};
        opcion = JOptionPane.showOptionDialog(PanelPrincipal, "Estas seguro de salir?", "cerrar ventana",JOptionPane.YES_NO_OPTION ,JOptionPane.INFORMATION_MESSAGE , null, textoBotones, EXIT_ON_CLOSE);
        
        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSalida = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cajaCodBodega = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cajaCantidadVenta = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cajaFechaVenta = new javax.swing.JTextField();
        jCalendarVenta = new com.toedter.calendar.JCalendar();
        btnActualizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btenSalir = new javax.swing.JButton();

        PanelPrincipal.setBackground(new java.awt.Color(255, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setText("Administrar Ventas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tablaSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSalidaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSalida);

        jLabel2.setText("Codigo Bodega");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cajaCodBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cajaCodBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel3.setText("Cantidad Venta");

        jLabel4.setText("Fecha Venta");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(cajaFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jCalendarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCalendarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cajaFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(cajaCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cajaCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        btenSalir.setText("X");
        btenSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btenSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(28, 28, 28)
                        .addComponent(btenSalir)
                        .addGap(28, 28, 28))))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizar)
                            .addComponent(jButton2)
                            .addComponent(btenSalir))))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSalidaMouseClicked
        int columnaseleccionada = tablaSalida.getSelectedColumn();

        if (columnaseleccionada == 4) {
            int filaSeleccionada = tablaSalida.getSelectedRow();
        String codigoTexto = miModelito.getValueAt(filaSeleccionada, 0).toString();

        int codigo = Integer.parseInt(codigoTexto);

        objVentas = objMiDao.buscar(codigo);

        if (objVentas == null) {
            JOptionPane.showMessageDialog(PanelPrincipal, "Fallo al obtener los datos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int codigoBodega = Integer.parseInt(cajaCodBodega.getText());
            LocalDate fechaVenta = LocalDate.parse(cajaFechaVenta.getText());
            
            Bodega bodega = new Bodega(codigoBodega, "", 0.0, 0.0);
            objVentas.setCodBodega(bodega);
            objVentas.setFechaVenta(fechaVenta);
            
            cajaCodBodega.setText(String.valueOf(objVentas.getCodBodega().getCodBodega()));
            cajaCantidadVenta.setText(String.valueOf(objVentas.getCantidadVenta()));
            cajaFechaVenta.setText(String.valueOf(objVentas.getFechaVenta()));
        }

        } else if (columnaseleccionada == 5) {// si se daclick en la columna 4 
            int filaSeleccionada = tablaSalida.getSelectedRow();
            String codigoTexto = miModelito.getValueAt(filaSeleccionada, 0).toString();// Extrae el valor en la columna 0 (presumiblemente el código) de la fila seleccionada y lo convierte a una cadena de texto.
            int codigo = Integer.parseInt(codigoTexto);//  Convierte la cadena de texto a un entero, asumiendo que representa un valor numérico.
            String[] textoBotones = {"Aceptar", "Cancelar"};// crea un array con el nombre de los botones
            int opcion = 0;
            // mensaje en el cuadro de advertencia
            opcion = JOptionPane.showOptionDialog(rootPane, "Estas seguro de eliminar el registro", "Eliminar Registro", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, textoBotones, textoBotones[1]);

            llenarTabla();// metodo para actualizar la tabla
            if (opcion == JOptionPane.YES_OPTION) {// si  el usuario da click en aceptar
                objMiDao.eliminar(codigo);// se llama al método eliminar del objeto objMiDao 
                llenarTabla();// se actaliza la tabla
            } else {// si da click en cancelar
                llenarTabla();// se acualiza la tabla
            }

        }
    }//GEN-LAST:event_tablaSalidaMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int codigoBodega;
        int cantidadVenta;
        LocalDate fechaVenta;

        codigoBodega = Integer.parseInt(cajaCodBodega.getText());
        cantidadVenta = parseInt(cajaCantidadVenta.getText());
        fechaVenta = LocalDate.parse(cajaFechaVenta.getText());

        if (codigoBodega <= 0 || cantidadVenta <= 0 || fechaVenta == null) {
            JOptionPane.showMessageDialog(PanelPrincipal, "Faltan datos para realizar la acutalizacio", "Advertensia", JOptionPane.WARNING_MESSAGE);

        } else {
            // Se crea un objeto Bodega con el código proporcionado por el usuario
            Bodega bodega = new Bodega(codigoBodega, "", 0.0, 0.0);

            // Se configuran los datos de la venta en el objeto objVentas
            objVentas.setCodBodega(bodega);
            objVentas.setCantidadVenta(cantidadVenta);
            objVentas.setFechaVenta(fechaVenta);

            boolean actualizado = objMiDao.actualizar(objVentas);

            if (actualizado) {

                JOptionPane.showMessageDialog(PanelPrincipal, "Se actualizo el permiso " +  " de forma correcta", "exito", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(PanelPrincipal, "fallo al actualizar el permiso ", "error", JOptionPane.ERROR_MESSAGE);

            }
            llenarTabla();

        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btenSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btenSalirActionPerformed
        this.cerrarVentana();
    }//GEN-LAST:event_btenSalirActionPerformed

    private void jCalendarVentaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendarVentaPropertyChange
        if ("calendar".equals(evt.getPropertyName())) {
            Date selectedDate = jCalendarVenta.getDate();
            if (selectedDate != null) {
                LocalDate fechaSeleccionada = selectedDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                String fechaFormateada = fechaSeleccionada.format(formatter);
                cajaFechaVenta.setText(fechaFormateada);
            }
        }
    }//GEN-LAST:event_jCalendarVentaPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btenSalir;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JTextField cajaCantidadVenta;
    private javax.swing.JTextField cajaCodBodega;
    private javax.swing.JTextField cajaFechaVenta;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendarVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSalida;
    // End of variables declaration//GEN-END:variables
}
