/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package edu.jdc.formularuios;

import edu.jdc.clases.Permiso;
import edu.jdc.daos.DaoPermiso;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FrmCrearPermiso extends javax.swing.JInternalFrame {

    private Permiso objpermiso;
    private  DaoPermiso objMiDao;
    
    public FrmCrearPermiso() {
        initComponents();
        
        objpermiso = new Permiso();
        objMiDao = new DaoPermiso();
        
        
    }
    private void limpiarCajas(){
        cajaNombrePermiso.setText("");
        cajaFuncionalidaPermiso.setText("");
        
        cajaFuncionalidaPermiso.requestFocus();
        
    } 
    private void cerrarVentana(){
        int opcion = 0;
        String[] textoBotones={"Aceptar", "Cancelar"};
        opcion = JOptionPane.showOptionDialog(rootPane, "Estas seguro de salir?", "cerrar ventana",JOptionPane.YES_NO_OPTION ,JOptionPane.INFORMATION_MESSAGE , null, textoBotones, EXIT_ON_CLOSE);
        
        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelNombrePermiso = new javax.swing.JPanel();
        lblNombrePermiso = new javax.swing.JLabel();
        cajaNombrePermiso = new javax.swing.JTextField();
        PanelNombrePermiso1 = new javax.swing.JPanel();
        lblNombrePermiso1 = new javax.swing.JLabel();
        cajaFuncionalidaPermiso = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        PanelTitulo.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro Permiso");

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel1)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTituloLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        PanelNombrePermiso.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblNombrePermiso.setText("Nombre Permiso");

        cajaNombrePermiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNombrePermisoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNombrePermisoLayout = new javax.swing.GroupLayout(PanelNombrePermiso);
        PanelNombrePermiso.setLayout(PanelNombrePermisoLayout);
        PanelNombrePermisoLayout.setHorizontalGroup(
            PanelNombrePermisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombrePermisoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelNombrePermisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNombrePermisoLayout.createSequentialGroup()
                        .addComponent(lblNombrePermiso)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cajaNombrePermiso))
                .addContainerGap())
        );
        PanelNombrePermisoLayout.setVerticalGroup(
            PanelNombrePermisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombrePermisoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombrePermiso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(cajaNombrePermiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelNombrePermiso1.setBackground(new java.awt.Color(255, 255, 255));
        PanelNombrePermiso1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblNombrePermiso1.setText("Funcionalidad Permiso");

        cajaFuncionalidaPermiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaFuncionalidaPermisoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNombrePermiso1Layout = new javax.swing.GroupLayout(PanelNombrePermiso1);
        PanelNombrePermiso1.setLayout(PanelNombrePermiso1Layout);
        PanelNombrePermiso1Layout.setHorizontalGroup(
            PanelNombrePermiso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombrePermiso1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelNombrePermiso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNombrePermiso1Layout.createSequentialGroup()
                        .addComponent(lblNombrePermiso1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cajaFuncionalidaPermiso))
                .addContainerGap())
        );
        PanelNombrePermiso1Layout.setVerticalGroup(
            PanelNombrePermiso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombrePermiso1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombrePermiso1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(cajaFuncionalidaPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Grabar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelNombrePermiso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelNombrePermiso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(112, 112, 112))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(PanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelNombrePermiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelNombrePermiso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaNombrePermisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNombrePermisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNombrePermisoActionPerformed

    private void cajaFuncionalidaPermisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaFuncionalidaPermisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaFuncionalidaPermisoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int opcion = 0;
        
        String[] textoBotones = {"Aceptar", "Cancelar"};
        
        opcion = JOptionPane.showOptionDialog(rootPane, "Estas seguro de cancelar el registro", "Cancelar Registro",JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE,null, textoBotones, textoBotones[1]);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.cerrarVentana();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre, funcionalidad;
        boolean registro;
        
        nombre = cajaNombrePermiso.getText();
        funcionalidad = cajaFuncionalidaPermiso.getText();
        
        if(nombre.isEmpty() || funcionalidad.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Faltan datos para completar el registro", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            objpermiso.setNombrePermiso(nombre);
            objpermiso.setFuncionalidadPermiso(funcionalidad);
            
            registro = objMiDao.registrar(objpermiso);
            
            if(registro){
                JOptionPane.showMessageDialog(rootPane, "registro de permiso" + nombre + "guardado en bd","Exito",  JOptionPane.INFORMATION_MESSAGE);
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Fallo en el registro de permiso", "Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelNombrePermiso;
    private javax.swing.JPanel PanelNombrePermiso1;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JTextField cajaFuncionalidaPermiso;
    private javax.swing.JTextField cajaNombrePermiso;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNombrePermiso;
    private javax.swing.JLabel lblNombrePermiso1;
    // End of variables declaration//GEN-END:variables
}
