/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.jdc.formularuios;

import edu.jdc.clases.Acceso;
import edu.jdc.clases.Usuario;
import edu.jdc.daos.DaoAcceso;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class FrmSesion extends javax.swing.JFrame {

    private DaoAcceso objMiDao;
    private  Usuario objUsuario;
    public FrmSesion() {
        initComponents();
        
        objMiDao = new DaoAcceso();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        PanelFormulario = new javax.swing.JPanel();
        PanelCajaCorreo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cajaCorreo = new javax.swing.JTextField();
        PanelCajaClave = new javax.swing.JPanel();
        lblClave = new javax.swing.JLabel();
        cajaClave = new javax.swing.JPasswordField();
        btnAccesder = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(255, 102, 51));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 102));
        lblTitulo.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        lblTitulo.setText("Happy Hen");

        PanelFormulario.setBackground(new java.awt.Color(255, 102, 102));

        PanelCajaCorreo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        jLabel1.setText("Correo Electronico");

        cajaCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCorreoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCajaCorreoLayout = new javax.swing.GroupLayout(PanelCajaCorreo);
        PanelCajaCorreo.setLayout(PanelCajaCorreoLayout);
        PanelCajaCorreoLayout.setHorizontalGroup(
            PanelCajaCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCajaCorreoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCajaCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        PanelCajaCorreoLayout.setVerticalGroup(
            PanelCajaCorreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCajaCorreoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cajaCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        lblClave.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        lblClave.setText("Contraseña");

        cajaClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaClaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCajaClaveLayout = new javax.swing.GroupLayout(PanelCajaClave);
        PanelCajaClave.setLayout(PanelCajaClaveLayout);
        PanelCajaClaveLayout.setHorizontalGroup(
            PanelCajaClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCajaClaveLayout.createSequentialGroup()
                .addGroup(PanelCajaClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCajaClaveLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblClave))
                    .addGroup(PanelCajaClaveLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cajaClave, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCajaClaveLayout.setVerticalGroup(
            PanelCajaClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCajaClaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClave)
                .addGap(18, 18, 18)
                .addComponent(cajaClave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnAccesder.setBackground(new java.awt.Color(255, 255, 0));
        btnAccesder.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        btnAccesder.setForeground(new java.awt.Color(255, 255, 255));
        btnAccesder.setText("Acceder");
        btnAccesder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccesderActionPerformed(evt);
            }
        });

        btnsalir.setBackground(new java.awt.Color(204, 0, 0));
        btnsalir.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setText("Salir");

        javax.swing.GroupLayout PanelFormularioLayout = new javax.swing.GroupLayout(PanelFormulario);
        PanelFormulario.setLayout(PanelFormularioLayout);
        PanelFormularioLayout.setHorizontalGroup(
            PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelCajaCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelCajaClave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PanelFormularioLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAccesder, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(btnsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelFormularioLayout.setVerticalGroup(
            PanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelCajaCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelCajaClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnAccesder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(PanelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cajaCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaCorreoActionPerformed

    private void cajaClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaClaveActionPerformed

    private void btnAccesderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccesderActionPerformed
        String correo, clave;
        
        correo = cajaCorreo.getText();
        clave = new String (cajaClave.getPassword());
        
        if (correo.isEmpty() || clave.isEmpty()){
            JOptionPane.showMessageDialog(PanelPrincipal, "faltan datos para el inicio de sesion", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            Acceso objAcceso = new Acceso();
            objAcceso.setCorreoAcceso(correo);
            objAcceso.setClaveUsuario(clave);
            
            objUsuario = objMiDao.iniciosesion(objAcceso);
            
            if (objUsuario != null){
                FrmPrincipa miVentana = new FrmPrincipa(objUsuario);
                miVentana.setVisible(true);
                this.dispose();
                
            }else{
                JOptionPane.showMessageDialog(PanelPrincipal, "fallo obtener credenciales", "error", JOptionPane.ERROR_MESSAGE);
                
            }
            
            
        }
    }//GEN-LAST:event_btnAccesderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCajaClave;
    private javax.swing.JPanel PanelCajaCorreo;
    private javax.swing.JPanel PanelFormulario;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btnAccesder;
    private javax.swing.JButton btnsalir;
    private javax.swing.JPasswordField cajaClave;
    private javax.swing.JTextField cajaCorreo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
